tasks:
  - name: ui
    init: echo "Hello, to manfromexitence/ui"
    command: npm install -g npm@10.8.3 && npm install -g bun && cd www && bun install && bun run dev && echo "Thanks for checking this codebase!"
